In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('Dataset of Diabetes .csv')

In [4]:
df.head()

,ID,No_Pation,Gender,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,CLASS
0,502,17975,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
1,735,34221,M,26,4.5,62,4.9,3.7,1.4,1.1,2.1,0.6,23.0,N
2,420,47975,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
3,680,87656,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
4,504,34223,M,33,7.1,46,4.9,4.9,1.0,0.8,2.0,0.4,21.0,N

In [ ]:
no NAN or Invalid values present in the dataset 

data attributes are Gender M/F ,age > 0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         1000 non-null   int64
 1   No_Pation  1000 non-null   int64
 2   Gender     1000 non-null   object
 3   AGE        1000 non-null   int64
 4   Urea       1000 non-null   float64
 5   Cr         1000 non-null   int64
 6   HbA1c      1000 non-null   float64
 7   Chol       1000 non-null   float64
 8   TG         1000 non-null   float64
 9   HDL        1000 non-null   float64
 10  LDL        1000 non-null   float64
 11  VLDL       1000 non-null   float64
 12  BMI        1000 non-null   float64
 13  CLASS      1000 non-null   object
dtypes: float64(8), int64(4), object(2)
memory usage: 109.5+ KB

In [6]:
print(df.describe())

                ID     No_Pation          AGE         Urea           Cr  \
count  1000.000000  1.000000e+03  1000.000000  1000.000000  1000.000000
mean    340.500000  2.705514e+05    53.528000     5.124743    68.943000
std     240.397673  3.380758e+06     8.799241     2.935165    59.984747
min       1.000000  1.230000e+02    20.000000     0.500000     6.000000
25%     125.750000  2.406375e+04    51.000000     3.700000    48.000000
50%     300.500000  3.439550e+04    55.000000     4.600000    60.000000
75%     550.250000  4.538425e+04    59.000000     5.700000    73.000000
max     800.000000  7.543566e+07    79.000000    38.900000   800.000000

             HbA1c         Chol           TG          HDL          LDL  \
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.000000
mean      8.281160     4.862820     2.349610     1.204750     2.609790
std       2.534003     1.301738     1.401176     0.660414     1.115102
min       0.900000     0.000000     0.300000     0.200000     0.300000
25%       6.500000     4.000000     1.500000     0.900000     1.800000
50%       8.000000     4.800000     2.000000     1.100000     2.500000
75%      10.200000     5.600000     2.900000     1.300000     3.300000
max      16.000000    10.300000    13.800000     9.900000     9.900000

              VLDL          BMI
count  1000.000000  1000.000000
mean      1.854700    29.578020
std       3.663599     4.962388
min       0.100000    19.000000
25%       0.700000    26.000000
50%       0.900000    30.000000
75%       1.500000    33.000000
max      35.000000    47.750000

In [10]:
df[df.isnull().any(axis = 1)]

Empty DataFrame
Columns: [ID, No_Pation, Gender, AGE, Urea, Cr, HbA1c, Chol, TG, HDL, LDL, VLDL, BMI, CLASS]
Index: []

In [17]:
columns_to_check =  ['AGE', 'Urea', 'Cr', 'HbA1c', 'Chol', 'TG', 'HDL', 'LDL', 'VLDL', 'BMI']


for column in columns_to_check:
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    # Identify outliers
    df = df[(df[column] >= lower_bound) & (df[column] <= upper_bound)]

In [20]:
from sklearn.preprocessing import LabelEncoder\

label_encoder = LabelEncoder()
df['Gender'] = label_encoder.fit_transform(df['Gender'])

df = pd.get_dummies(df, columns=['CLASS'], drop_first=True)

In [23]:
df = df.reset_index()
print(df)

     level_0  index   ID  No_Pation  Gender  AGE  Urea  Cr  HbA1c  Chol   TG  \
0          0      5  634      34224       0   45   2.3  24    4.0   2.9  1.0
1          1      6  721      34225       0   50   2.0  50    4.0   3.6  1.3
2          2      7  421      34227       1   48   4.7  47    4.0   2.9  0.8
3          3     13  132      34234       0   45   4.6  54    5.1   4.2  1.7
4          4     14  402      34235       0   50   3.5  39    4.0   4.0  1.5
..       ...    ...  ...        ...     ...  ...   ...  ..    ...   ...  ...
673      673    989  193     454316       1   62   6.3  82    6.7   5.3  2.0
674      674    990  194     454316       0   57   4.1  70    9.3   5.3  3.3
675      675    991  195       4543       2   55   4.1  34   13.9   5.4  1.6
676      676    992  196     454316       1   55   3.1  39    8.5   5.0  2.5
677      677    999  248      24054       1   54   5.0  67    6.9   3.8  1.7

     HDL  LDL  VLDL   BMI  CLASS_P  CLASS_Y  CLASS_Y
0    1.0  1.5   0.4  21.0    False    False     False
1    0.9  2.1   0.6  24.0    False    False     False
2    0.9  1.6   0.4  24.0    False    False     False
3    1.2  2.2   0.8  23.0    False    False     False
4    1.2  2.2   0.7  24.0    False    False     False
..   ...  ...   ...   ...      ...      ...       ...
673  1.0  3.5   0.9  30.1    False     True     False
674  1.0  1.4   1.3  29.0    False     True     False
675  1.6  3.1   0.7  33.0    False     True     False
676  1.9  2.9   0.7  27.0    False     True     False
677  1.1  3.0   0.7  33.0    False    False      True

[678 rows x 18 columns]

In [24]:
from sklearn.preprocessing import MinMaxScaler

# Initialize MinMaxScaler
min_max_scaler = MinMaxScaler()

# List of numerical columns to normalize
numerical_cols = ['AGE', 'Urea', 'Cr', 'HbA1c', 'Chol', 'TG', 'HDL', 'LDL', 'VLDL', 'BMI']

# Apply Min-Max scaling
df[numerical_cols] = min_max_scaler.fit_transform(df[numerical_cols])

# Check the transformed values
print(df[numerical_cols].head())

        AGE      Urea        Cr     HbA1c      Chol        TG       HDL  \
0  0.193548  0.157895  0.023810  0.153846  0.152542  0.148936  0.400000
1  0.354839  0.118421  0.333333  0.153846  0.271186  0.212766  0.333333
2  0.290323  0.473684  0.297619  0.153846  0.152542  0.106383  0.333333
3  0.193548  0.460526  0.380952  0.238462  0.372881  0.297872  0.533333
4  0.354839  0.315789  0.202381  0.153846  0.338983  0.255319  0.533333

        LDL      VLDL   BMI
0  0.183673  0.142857  0.10
1  0.306122  0.238095  0.25
2  0.204082  0.142857  0.25
3  0.326531  0.333333  0.20
4  0.326531  0.285714  0.25

In [25]:
from sklearn.preprocessing import StandardScaler

# Initialize StandardScaler
scaler = StandardScaler()

# Apply StandardScaler to the numerical columns
df[numerical_cols] = scaler.fit_transform(df[numerical_cols])

# Check the transformed values
print(df[numerical_cols].head())

        AGE      Urea        Cr     HbA1c      Chol        TG       HDL  \
0 -1.753828 -1.540818 -1.978741 -1.742885 -1.694275 -1.136204 -0.355027
1 -0.860309 -1.746638 -0.468142 -1.742885 -1.064840 -0.834738 -0.671624
2 -1.217716  0.105743 -0.642442 -1.742885 -1.694275 -1.337181 -0.671624
3 -1.753828  0.037137 -0.235742 -1.306250 -0.525325 -0.432783  0.278166
4 -0.860309 -0.717537 -1.107242 -1.742885 -0.705163 -0.633760  0.278166

        LDL      VLDL       BMI
0 -1.080399 -1.329300 -1.859480
1 -0.474092 -0.882687 -1.205474
2 -0.979348 -1.329300 -1.205474
3 -0.373040 -0.436074 -1.423476
4 -0.373040 -0.659380 -1.205474

In [27]:
import pandas as pd
import numpy as np

df = pd.read_csv('adult.csv')

# Assuming your DataFrame is named df
df.replace('?', np.nan, inplace=True)

In [28]:
numerical_cols = ['age', 'fnlwgt', 'educational-num', 'capital-gain', 'capital-loss', 'hours-per-week']
df[numerical_cols] = df[numerical_cols].fillna(df[numerical_cols].median())

In [29]:
df = df.dropna(subset=numerical_cols)

In [30]:
# Impute missing categorical values with mode
categorical_cols = ['workclass', 'education', 'marital-status', 'occupation', 
                    'relationship', 'race', 'gender', 'native-country', 'income']
for col in categorical_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [31]:
print(df.head())

   age  workclass  fnlwgt     education  educational-num      marital-status  \
0   25    Private  226802          11th                7       Never-married
1   38    Private   89814       HS-grad                9  Married-civ-spouse
2   28  Local-gov  336951    Assoc-acdm               12  Married-civ-spouse
3   44    Private  160323  Some-college               10  Married-civ-spouse
4   18    Private  103497  Some-college               10       Never-married

          occupation relationship   race  gender  capital-gain  capital-loss  \
0  Machine-op-inspct    Own-child  Black    Male             0             0
1    Farming-fishing      Husband  White    Male             0             0
2    Protective-serv      Husband  White    Male             0             0
3  Machine-op-inspct      Husband  Black    Male          7688             0
4     Prof-specialty    Own-child  White  Female             0             0

   hours-per-week native-country income
0              40  United-States  <=50K
1              50  United-States  <=50K
2              40  United-States   >50K
3              40  United-States   >50K
4              30  United-States  <=50K